<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Symfony\Component\HttpFoundation\Request;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQueryBuilder(Request $request)
    {
        $qb = $this->_em->getRepository(User::class)->createQueryBuilder('u');
        if ($request->query->get('filter')) {
            $qb
                ->where('u.username LIKE :filter OR u.email LIKE :filter')
                ->setParameter('filter','%'.$request->query->get('filter').'%');
        }
        return $qb;
    }
}
